---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neural-day-api
  namespace: api-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neural-day-api
  template:
    metadata:
      labels:
        app: neural-day-api
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: neural-day-api
        image: IMAGE_NAME_TO_BE_REPLACED
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
            memory: 180Mi
          limits:
            cpu: 500m
            memory: 500Mi



