apiVersion: apps/v1
kind: Deployment
metadata:
  name: neural-day-api
  namespace: api-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neural-day-api
  template:
    metadata:
      labels:
        app: neural-day-api
    spec:
      containers:
      - name: neural-day-api
        image: demo-dab631720210206184959
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 50m
            memory: 180Mi
          limits:
            cpu: 500m
            memory: 500Mi
kind: Service
apiVersion: apps/v1
metadata:
  name: neural-day-api
  namespace: api-demo

spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 9090
  selector:
    app: neural-day-api
  clusterIP: 10.245.134.221
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}

